export const translations = {
  en: {
    title: "Campus Buddy",
    login: "Login",
    logout: "Logout",
    rollNo: "Roll Number",
    pass: "Password",
    enter: "Enter",
    welcome: "Welcome, Student",
    searchPlaceholder: "Ask anything about admissions, library, IT, classes...",
    askBtn: "Ask",
    responseTitle: "Buddy's Answer:",
    greeting: "Hi! I'm Campus Buddy 🌻 Ask me about admissions, library hours, IT support, classes, anything campus-related.",
    tryAsking: "✨ Try asking",
    sug1: "When is the financial aid deadline?",
    sug2: "How many books can I borrow?",
    sug3: "How do I reset my password?",
    sug4: "What is the GPA needed to graduate?",
    guide: "✨ Your friendly guide to college life",
    signInTitle: "Sign in to continue your campus journey",
    regStudents: "Registered students",
    activeUsers: "Active in last 24h",
    createAcc: "Create Account",
    welcomeBack: "Welcome back",
    emailRoll: "Email / Roll Number",
    resetPassTitle: "Reset Password",
    enterEmailPass: "Enter your email and new password",
    registerToStart: "Register to get started",
    alreadyHave: "Already have an account? Log In",
    newStudent: "New student? Create an account",
    forgotPass: "Forgot Password?",
    backToLogin: "Back to Login",
    newPass: "New Password",
    resetBtn: "Reset Password",
    registerBtn: "Register"
  },
  hi: {
    title: "कैंपस बडी",
    login: "लॉगिन",
    logout: "लॉगआउट",
    rollNo: "रोल नंबर",
    pass: "पासवर्ड",
    enter: "प्रवेश करें",
    welcome: "स्वागत है, छात्र",
    searchPlaceholder: "एडमिशन, लाइब्रेरी, आईटी, कक्षाओं के बारे में कुछ भी पूछें...",
    askBtn: "पूछें",
    responseTitle: "बडी का जवाब:",
    greeting: "नमस्ते! मैं कैंपस बडी हूँ 🌻 मुझसे प्रवेश, पुस्तकालय के समय, आईटी सहायता, कक्षाओं, या कैंपस से जुड़ी किसी भी चीज़ के बारे में पूछें।",
    tryAsking: "✨ पूछने का प्रयास करें",
    sug1: "वित्तीय सहायता की समय सीमा कब है?",
    sug2: "मैं कितनी किताबें उधार ले सकता हूँ?",
    sug3: "मैं अपना पासवर्ड कैसे रीसेट करूँ?",
    sug4: "स्नातक होने के लिए कितने GPA की आवश्यकता है?",
    guide: "✨ कॉलेज जीवन के लिए आपका मार्गदर्शक",
    signInTitle: "अपनी कैंपस यात्रा जारी रखने के लिए साइन इन करें",
    regStudents: "पंजीकृत छात्र",
    activeUsers: "पिछले 24 घंटों में सक्रिय",
    createAcc: "खाता बनाएं",
    welcomeBack: "वापसी पर स्वागत है",
    emailRoll: "ईमेल / रोल नंबर",
    resetPassTitle: "पासवर्ड रीसेट करें",
    enterEmailPass: "अपना ईमेल और नया पासवर्ड दर्ज करें",
    registerToStart: "शुरू करने के लिए रजिस्टर करें",
    alreadyHave: "क्या आपके पास पहले से खाता है? लॉग इन करें",
    newStudent: "नए छात्र? एक खाता बनाएं",
    forgotPass: "पासवर्ड भूल गए?",
    backToLogin: "लॉगिन पर वापस जाएं",
    newPass: "नया पासवर्ड",
    resetBtn: "पासवर्ड रीसेट करें",
    registerBtn: "रजिस्टर करें"
  },
  te: {
    title: "క్యాంపస్ బడ్డీ",
    login: "లాగిన్",
    logout: "లాగ్ అవుట్",
    rollNo: "రోల్ నంబర్",
    pass: "పాస్‌వర్డ్",
    enter: "ప్రవేశించండి",
    welcome: "స్వాగతం, విద్యార్థి",
    searchPlaceholder: "అడ్మిషన్లు, లైబ్రరీ, IT, తరగతుల గురించి ఏదైనా అడగండి...",
    askBtn: "అడగండి",
    responseTitle: "బడ్డీ సమాధానం:",
    greeting: "హాయ్! నేను క్యాంపస్ బడ్డీని 🌻 అడ్మిషన్లు, లైబ్రరీ వేళలు, IT సపోర్ట్, తరగతులు, క్యాంపస్‌కు సంబంధించిన దేని గురించైనా నన్ను అడగండి.",
    tryAsking: "✨ అడగడానికి ప్రయత్నించండి",
    sug1: "ఆర్థిక సహాయం గడువు ఎప్పుడు?",
    sug2: "నేను ఎన్ని పుస్తకాలను అరువు తీసుకోవచ్చు?",
    sug3: "నా పాస్‌వర్డ్‌ను నేను ఎలా రీసెట్ చేయాలి?",
    sug4: "గ్రాడ్యుయేట్ కావడానికి ఎంత GPA అవసరం?",
    guide: "✨ కళాశాల జీవితానికి మీ స్నేహపూర్వక గైడ్",
    signInTitle: "మీ క్యాంపస్ ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి",
    regStudents: "నమోదిత విద్యార్థులు",
    activeUsers: "గత 24 గంటల్లో యాక్టివ్‌గా ఉన్నారు",
    createAcc: "ఖాతాను సృష్టించండి",
    welcomeBack: "స్వాగతం",
    emailRoll: "ఇమెయిల్ / రోల్ నంబర్",
    resetPassTitle: "పాస్‌వర్డ్‌ను రీసెట్ చేయండి",
    enterEmailPass: "మీ ఇమెయిల్ మరియు కొత్త పాస్‌వర్డ్‌ను నమోదు చేయండి",
    registerToStart: "ప్రారంభించడానికి నమోదు చేయండి",
    alreadyHave: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి",
    newStudent: "కొత్త విద్యార్థా? ఖాతాను సృష్టించండి",
    forgotPass: "పాస్‌వర్డ్ మర్చిపోయారా?",
    backToLogin: "లాగిన్‌కి తిరిగి వెళ్లండి",
    newPass: "కొత్త పాస్‌వర్డ్",
    resetBtn: "పాస్‌వర్డ్ రీసెట్ చేయండి",
    registerBtn: "నమోదు చేయండి"
  }
};